### ISSUE TITLE
How to get badge to display

### ISSUE THREAD

**Issue by tgsmith61591** [kt3k/coveralls-gradle-plugin#57]
Hey, I used your coveralls wrapper on my java project and it worked seamlessly. Thank you so much! My question (and it's likely an extremely naive one...) is how to get the coverage badge? It seems like it didn't execute on coveralls.

[Here](https://github.com/tgsmith61591/clust4j) is my repo. Here's what my .travis.yml file looks like:

```
language: java
jdk:
  - oraclejdk7

branches:
  only:
    - master

before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"

after_failure:
  - cat target/surefire-reports/*.txt

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
- ./gradlew cobertura coveralls
```

And I have the following line at the head of my `build.gradle`:

```
plugins {
    // ... other plugins
    // coverage tools
    id 'net.saliman.cobertura' version '2.3.1'
    id 'com.github.kt3k.coveralls' version '2.6.3'
}
cobertura.coverageFormats = ['html', 'xml'] // coveralls plugin depends on xml format report
```

And yet, I'm still getting the `coverage | unknown` badge in my `README`. Any thoughts?
